ACCOUNT = <AWS Accoutn Id>
REGION = <AWS Region>
PROJECTNAME = <name>
SLACK_VERIFICATION_TOKEN = <slack verification token>
SLACK_TEAM_ID = <slack team id>
COMMAND_NAME = <slack command name>
LANGUAGE = <lambda programming language>
PATH_TO_HANDLER = <path to handler>
HANDLER = <callable handler e.g. "index.handler">
STACK_ROOT = slack-$(ACCOUNT)-$(PROJECTNAME)